name: Build and publish to PyPI

on:
  workflow_dispatch:

  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build source and wheel distributions
        run: python -m build

      - name: Check the built packages
        run: python -m twine check dist/*
        
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1